version: '3.8'

# This file contains settings specific developing inside the containers

services:
  timescaledb:
    #platform: linux/amd64 
    image: timescale/timescaledb-ha:pg16
    volumes:
      - .:/workspace
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 10

  shadowtraffic:
    depends_on:
      timescaledb:
        condition: service_healthy
    image: shadowtraffic/shadowtraffic:latest
    #entrypoint: sleep infinity
    restart: always 
    entrypoint: ["java", "-jar", "/home/shadowtraffic.jar"]
    command: ["--config", "./sensors.json"]
    volumes:
      - .:/workspace
      - ./streamdata/sensors.json:./sensors.json
    environment:
      - LICENSE_ID=e44ffe2f-bc96-4000-86dc-0c3903ad582d
      - LICENSE_EMAIL=jsewell@timescale.com
      - LICENSE_ORGANIZATION=Timescale
      - LICENSE_EDITION=ShadowTraffic Free Trial
      - LICENSE_EXPIRATION=2024-05-08
      - LICENSE_SIGNATURE=XZtcAnnZgM/WeBhH9mWT/kVpdtAoQvfaD3jN1a/KjFQtJkzN4srBZqEQ5+VTqYxMny6AU0gIGIOedoxzXGCMmyzAXEC5XBIBhoxZrMlnirdniyhmVNyTR+/+eQlRgE42UN6fUkTg+m6e3Qy++BBKR2TQ2MAZub+Tagos9BYh80DCNQopkXzprsm+7rsR4y5KBuLlAhOKpw+Re+0XsyMYSTVbTx055MJrq2wkvQqMwpoItLbqEEy7GFzSf6sToktnpZ46oNlVmqcp8FIJSMU5JRj8C6Uo92x1xZP71jYQVdUh1/8RMt+vmn/LrNWzsWNUsUdJ34q0cwjEnJW4D6I8GA==
