version: '3.8'

# This file contains settings specific developing inside the containers

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    volumes:
      - .:/workspace
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      timeout: 10s
      retries: 10

  shadowtraffic:
    depends_on:
      timescaledb:
        condition: service_healthy
    image: shadowtraffic/shadowtraffic:latest
    restart: always 
    entrypoint: ["java", "-jar", "/home/shadowtraffic.jar"]
    command: ["--config", "/workspace/sensors.json"]
    volumes:
      - .:/workspace
    environment:
      - LICENSE_ID=d177fa5b-441f-4b20-8792-af903e495d70
      - LICENSE_EMAIL=jsewell@timescale.com
      - LICENSE_ORGANIZATION=Timescale
      - LICENSE_EDITION=ShadowTraffic Free Trial
      - LICENSE_EXPIRATION=2024-12-01
      - LICENSE_SIGNATURE=xfhrs9WC4qMdniapz1p1sxBC/Q8gjJOSIbt/TFoxVQ40+O6RUvQX6JuJ8+AMRBH5whv+FUYdofUOjCQ1Wmb9Gnvc+Le2qRN1BeW+eMtg5g0+D39ICbHUrtgfLP5kGO14lTgjWRTdtDuCrvlDfX6Nxj8x+XK46j/UWJF7AohTpg9fT2tp3Vks0DnJENUSUX90qIh4/9hLurWap7P0rt2zXjSeUzlaNXLe+pIUTNrRXtQnVkgz6GQwFnh3JZqsg4cfJhQ9X+flfiDiz0SHmICT2JjDVaOME5wS98/xptHp6qKUL6q0aKPaJaYAMuX7idH9okgrhifxjy1r3d7Uyc9tyg==
